<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RestaurantProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            ['restaurant_id' => 1, 'product_id' => 1], ['restaurant_id' => 2, 'product_id' => 1], ['restaurant_id' => 3, 'product_id' => 1],
            ['restaurant_id' => 4, 'product_id' => 1], ['restaurant_id' => 5, 'product_id' => 1], ['restaurant_id' => 6, 'product_id' => 1],
            ['restaurant_id' => 7, 'product_id' => 1], ['restaurant_id' => 8, 'product_id' => 1], ['restaurant_id' => 9, 'product_id' => 1],
            ['restaurant_id' => 10, 'product_id' => 1], ['restaurant_id' => 11, 'product_id' => 1], ['restaurant_id' => 12, 'product_id' => 1],
            ['restaurant_id' => 13, 'product_id' => 1], ['restaurant_id' => 14, 'product_id' => 1], ['restaurant_id' => 15, 'product_id' => 1],
            ['restaurant_id' => 16, 'product_id' => 1], ['restaurant_id' => 17, 'product_id' => 1], ['restaurant_id' => 18, 'product_id' => 1],
            ['restaurant_id' => 19, 'product_id' => 1], ['restaurant_id' => 20, 'product_id' => 1], ['restaurant_id' => 21, 'product_id' => 1],
            ['restaurant_id' => 22, 'product_id' => 1], ['restaurant_id' => 23, 'product_id' => 1], ['restaurant_id' => 24, 'product_id' => 1],
            ['restaurant_id' => 25, 'product_id' => 1], ['restaurant_id' => 26, 'product_id' => 1], ['restaurant_id' => 27, 'product_id' => 1],
            ['restaurant_id' => 28, 'product_id' => 1], ['restaurant_id' => 29, 'product_id' => 1], ['restaurant_id' => 30, 'product_id' => 1],
            ['restaurant_id' => 31, 'product_id' => 1], ['restaurant_id' => 32, 'product_id' => 1], ['restaurant_id' => 33, 'product_id' => 1],
            ['restaurant_id' => 34, 'product_id' => 1], ['restaurant_id' => 2, 'product_id' => 2], ['restaurant_id' => 3, 'product_id' => 2],
            ['restaurant_id' => 6, 'product_id' => 2], ['restaurant_id' => 7, 'product_id' => 2], ['restaurant_id' => 8, 'product_id' => 2],
            ['restaurant_id' => 9, 'product_id' => 2], ['restaurant_id' => 10, 'product_id' => 2], ['restaurant_id' => 11, 'product_id' => 2],
            ['restaurant_id' => 12, 'product_id' => 2], ['restaurant_id' => 13, 'product_id' => 2], ['restaurant_id' => 15, 'product_id' => 2],
            ['restaurant_id' => 18, 'product_id' => 2], ['restaurant_id' => 20, 'product_id' => 2], ['restaurant_id' => 23, 'product_id' => 2],
            ['restaurant_id' => 24, 'product_id' => 2], ['restaurant_id' => 25, 'product_id' => 2], ['restaurant_id' => 26, 'product_id' => 2],
            ['restaurant_id' => 30, 'product_id' => 2], ['restaurant_id' => 2, 'product_id' => 3], ['restaurant_id' => 3, 'product_id' => 3],
            ['restaurant_id' => 6, 'product_id' => 3], ['restaurant_id' => 7, 'product_id' => 3], ['restaurant_id' => 8, 'product_id' => 3],
            ['restaurant_id' => 9, 'product_id' => 3], ['restaurant_id' => 10, 'product_id' => 3], ['restaurant_id' => 11, 'product_id' => 3],
            ['restaurant_id' => 12, 'product_id' => 3], ['restaurant_id' => 13, 'product_id' => 3], ['restaurant_id' => 15, 'product_id' => 3],
            ['restaurant_id' => 18, 'product_id' => 3], ['restaurant_id' => 20, 'product_id' => 3], ['restaurant_id' => 23, 'product_id' => 3],
            ['restaurant_id' => 24, 'product_id' => 3], ['restaurant_id' => 25, 'product_id' => 3], ['restaurant_id' => 26, 'product_id' => 3],
            ['restaurant_id' => 30, 'product_id' => 3], ['restaurant_id' => 2, 'product_id' => 4], ['restaurant_id' => 3, 'product_id' => 4],
            ['restaurant_id' => 6, 'product_id' => 4], ['restaurant_id' => 7, 'product_id' => 4], ['restaurant_id' => 8, 'product_id' => 4],
            ['restaurant_id' => 9, 'product_id' => 4], ['restaurant_id' => 10, 'product_id' => 4], ['restaurant_id' => 11, 'product_id' => 4],
            ['restaurant_id' => 12, 'product_id' => 4], ['restaurant_id' => 13, 'product_id' => 4], ['restaurant_id' => 15, 'product_id' => 4],
            ['restaurant_id' => 18, 'product_id' => 4], ['restaurant_id' => 20, 'product_id' => 4], ['restaurant_id' => 23, 'product_id' => 4],
            ['restaurant_id' => 24, 'product_id' => 4], ['restaurant_id' => 25, 'product_id' => 4], ['restaurant_id' => 26, 'product_id' => 4],
            ['restaurant_id' => 30, 'product_id' => 4], ['restaurant_id' => 2, 'product_id' => 5], ['restaurant_id' => 3, 'product_id' => 5],
            ['restaurant_id' => 6, 'product_id' => 5], ['restaurant_id' => 7, 'product_id' => 5], ['restaurant_id' => 8, 'product_id' => 5],
            ['restaurant_id' => 9, 'product_id' => 5], ['restaurant_id' => 10, 'product_id' => 5], ['restaurant_id' => 11, 'product_id' => 5],
            ['restaurant_id' => 12, 'product_id' => 5], ['restaurant_id' => 13, 'product_id' => 5], ['restaurant_id' => 15, 'product_id' => 5],
            ['restaurant_id' => 18, 'product_id' => 5], ['restaurant_id' => 20, 'product_id' => 5], ['restaurant_id' => 23, 'product_id' => 5],
            ['restaurant_id' => 24, 'product_id' => 5], ['restaurant_id' => 25, 'product_id' => 5], ['restaurant_id' => 26, 'product_id' => 5],
            ['restaurant_id' => 30, 'product_id' => 5], ['restaurant_id' => 2, 'product_id' => 6], ['restaurant_id' => 3, 'product_id' => 6],
            ['restaurant_id' => 6, 'product_id' => 6], ['restaurant_id' => 7, 'product_id' => 6], ['restaurant_id' => 8, 'product_id' => 6],
            ['restaurant_id' => 9, 'product_id' => 6], ['restaurant_id' => 10, 'product_id' => 6], ['restaurant_id' => 11, 'product_id' => 6],
            ['restaurant_id' => 12, 'product_id' => 6], ['restaurant_id' => 13, 'product_id' => 6], ['restaurant_id' => 15, 'product_id' => 6],
            ['restaurant_id' => 18, 'product_id' => 6], ['restaurant_id' => 20, 'product_id' => 6], ['restaurant_id' => 23, 'product_id' => 6],
            ['restaurant_id' => 24, 'product_id' => 6], ['restaurant_id' => 25, 'product_id' => 6], ['restaurant_id' => 26, 'product_id' => 6],
            ['restaurant_id' => 30, 'product_id' => 6], ['restaurant_id' => 2, 'product_id' => 7], ['restaurant_id' => 3, 'product_id' => 7],
            ['restaurant_id' => 6, 'product_id' => 7], ['restaurant_id' => 7, 'product_id' => 7], ['restaurant_id' => 8, 'product_id' => 7],
            ['restaurant_id' => 9, 'product_id' => 7], ['restaurant_id' => 10, 'product_id' => 7], ['restaurant_id' => 11, 'product_id' => 7],
            ['restaurant_id' => 12, 'product_id' => 7], ['restaurant_id' => 13, 'product_id' => 7], ['restaurant_id' => 15, 'product_id' => 7],
            ['restaurant_id' => 18, 'product_id' => 7], ['restaurant_id' => 20, 'product_id' => 7], ['restaurant_id' => 23, 'product_id' => 7],
            ['restaurant_id' => 24, 'product_id' => 7], ['restaurant_id' => 25, 'product_id' => 7], ['restaurant_id' => 1, 'product_id' => 8],
            ['restaurant_id' => 2, 'product_id' => 8], ['restaurant_id' => 3, 'product_id' => 8], ['restaurant_id' => 4, 'product_id' => 8],
            ['restaurant_id' => 5, 'product_id' => 8], ['restaurant_id' => 6, 'product_id' => 8], ['restaurant_id' => 7, 'product_id' => 8],
            ['restaurant_id' => 8, 'product_id' => 8], ['restaurant_id' => 9, 'product_id' => 8], ['restaurant_id' => 10, 'product_id' => 8],
            ['restaurant_id' => 11, 'product_id' => 8], ['restaurant_id' => 12, 'product_id' => 8], ['restaurant_id' => 13, 'product_id' => 8],
            ['restaurant_id' => 14, 'product_id' => 8], ['restaurant_id' => 15, 'product_id' => 8], ['restaurant_id' => 16, 'product_id' => 8],
            ['restaurant_id' => 17, 'product_id' => 8], ['restaurant_id' => 18, 'product_id' => 8], ['restaurant_id' => 19, 'product_id' => 8],
            ['restaurant_id' => 20, 'product_id' => 8], ['restaurant_id' => 21, 'product_id' => 8], ['restaurant_id' => 22, 'product_id' => 8],
            ['restaurant_id' => 23, 'product_id' => 8], ['restaurant_id' => 24, 'product_id' => 8], ['restaurant_id' => 25, 'product_id' => 8],
            ['restaurant_id' => 26, 'product_id' => 8], ['restaurant_id' => 27, 'product_id' => 8], ['restaurant_id' => 28, 'product_id' => 8],
            ['restaurant_id' => 29, 'product_id' => 8], ['restaurant_id' => 30, 'product_id' => 8], ['restaurant_id' => 31, 'product_id' => 8],
            ['restaurant_id' => 32, 'product_id' => 8], ['restaurant_id' => 33, 'product_id' => 8], ['restaurant_id' => 34, 'product_id' => 8],
            ['restaurant_id' => 18, 'product_id' => 9], ['restaurant_id' => 19, 'product_id' => 9], ['restaurant_id' => 21, 'product_id' => 9],
            ['restaurant_id' => 23, 'product_id' => 9], ['restaurant_id' => 26, 'product_id' => 9], ['restaurant_id' => 27, 'product_id' => 9],
            ['restaurant_id' => 2, 'product_id' => 10], ['restaurant_id' => 3, 'product_id' => 10], ['restaurant_id' => 6, 'product_id' => 10],
            ['restaurant_id' => 7, 'product_id' => 10], ['restaurant_id' => 8, 'product_id' => 10], ['restaurant_id' => 9, 'product_id' => 10],
            ['restaurant_id' => 10, 'product_id' => 10], ['restaurant_id' => 11, 'product_id' => 10], ['restaurant_id' => 12, 'product_id' => 10],
            ['restaurant_id' => 13, 'product_id' => 10], ['restaurant_id' => 15, 'product_id' => 10], ['restaurant_id' => 18, 'product_id' => 10],
            ['restaurant_id' => 20, 'product_id' => 10], ['restaurant_id' => 23, 'product_id' => 10], ['restaurant_id' => 24, 'product_id' => 10],
            ['restaurant_id' => 25, 'product_id' => 10], ['restaurant_id' => 26, 'product_id' => 10], ['restaurant_id' => 30, 'product_id' => 10],
            ['restaurant_id' => 1, 'product_id' => 11], ['restaurant_id' => 2, 'product_id' => 11], ['restaurant_id' => 3, 'product_id' => 11],
            ['restaurant_id' => 4, 'product_id' => 11], ['restaurant_id' => 5, 'product_id' => 11], ['restaurant_id' => 6, 'product_id' => 11],
            ['restaurant_id' => 7, 'product_id' => 11], ['restaurant_id' => 8, 'product_id' => 11], ['restaurant_id' => 9, 'product_id' => 11],
            ['restaurant_id' => 10, 'product_id' => 11], ['restaurant_id' => 11, 'product_id' => 11], ['restaurant_id' => 12, 'product_id' => 11],
            ['restaurant_id' => 13, 'product_id' => 11], ['restaurant_id' => 14, 'product_id' => 11], ['restaurant_id' => 15, 'product_id' => 11],
            ['restaurant_id' => 16, 'product_id' => 11], ['restaurant_id' => 17, 'product_id' => 11], ['restaurant_id' => 18, 'product_id' => 11],
            ['restaurant_id' => 19, 'product_id' => 11], ['restaurant_id' => 20, 'product_id' => 11], ['restaurant_id' => 21, 'product_id' => 11],
            ['restaurant_id' => 22, 'product_id' => 11], ['restaurant_id' => 23, 'product_id' => 11], ['restaurant_id' => 24, 'product_id' => 11],
            ['restaurant_id' => 25, 'product_id' => 11], ['restaurant_id' => 26, 'product_id' => 11], ['restaurant_id' => 27, 'product_id' => 11],
            ['restaurant_id' => 28, 'product_id' => 11], ['restaurant_id' => 29, 'product_id' => 11], ['restaurant_id' => 30, 'product_id' => 11],
            ['restaurant_id' => 31, 'product_id' => 11], ['restaurant_id' => 32, 'product_id' => 11], ['restaurant_id' => 33, 'product_id' => 11],
            ['restaurant_id' => 34, 'product_id' => 11], ['restaurant_id' => 2, 'product_id' => 12], ['restaurant_id' => 3, 'product_id' => 12],
            ['restaurant_id' => 6, 'product_id' => 12], ['restaurant_id' => 7, 'product_id' => 12], ['restaurant_id' => 8, 'product_id' => 12],
            ['restaurant_id' => 9, 'product_id' => 12], ['restaurant_id' => 10, 'product_id' => 12], ['restaurant_id' => 11, 'product_id' => 12],
            ['restaurant_id' => 12, 'product_id' => 12], ['restaurant_id' => 13, 'product_id' => 12], ['restaurant_id' => 15, 'product_id' => 12],
            ['restaurant_id' => 18, 'product_id' => 12], ['restaurant_id' => 20, 'product_id' => 12], ['restaurant_id' => 23, 'product_id' => 12],
            ['restaurant_id' => 24, 'product_id' => 12], ['restaurant_id' => 25, 'product_id' => 12], ['restaurant_id' => 26, 'product_id' => 12],
            ['restaurant_id' => 30, 'product_id' => 12], ['restaurant_id' => 2, 'product_id' => 13], ['restaurant_id' => 3, 'product_id' => 13],
            ['restaurant_id' => 6, 'product_id' => 13], ['restaurant_id' => 7, 'product_id' => 13], ['restaurant_id' => 8, 'product_id' => 13],
            ['restaurant_id' => 9, 'product_id' => 13], ['restaurant_id' => 10, 'product_id' => 13], ['restaurant_id' => 11, 'product_id' => 13],
            ['restaurant_id' => 12, 'product_id' => 13], ['restaurant_id' => 13, 'product_id' => 13], ['restaurant_id' => 15, 'product_id' => 13],
            ['restaurant_id' => 18, 'product_id' => 13], ['restaurant_id' => 20, 'product_id' => 13], ['restaurant_id' => 23, 'product_id' => 13],
            ['restaurant_id' => 24, 'product_id' => 13], ['restaurant_id' => 25, 'product_id' => 13], ['restaurant_id' => 26, 'product_id' => 13],
            ['restaurant_id' => 30, 'product_id' => 13], ['restaurant_id' => 4, 'product_id' => 14], ['restaurant_id' => 5, 'product_id' => 14],
            ['restaurant_id' => 19, 'product_id' => 14], ['restaurant_id' => 21, 'product_id' => 14], ['restaurant_id' => 25, 'product_id' => 14],
            ['restaurant_id' => 26, 'product_id' => 14], ['restaurant_id' => 27, 'product_id' => 14], ['restaurant_id' => 28, 'product_id' => 14],
            ['restaurant_id' => 29, 'product_id' => 14], ['restaurant_id' => 30, 'product_id' => 14], ['restaurant_id' => 31, 'product_id' => 14],
            ['restaurant_id' => 4, 'product_id' => 15], ['restaurant_id' => 5, 'product_id' => 15], ['restaurant_id' => 13, 'product_id' => 15],
            ['restaurant_id' => 18, 'product_id' => 15], ['restaurant_id' => 19, 'product_id' => 15], ['restaurant_id' => 21, 'product_id' => 15],
            ['restaurant_id' => 27, 'product_id' => 15], ['restaurant_id' => 28, 'product_id' => 15], ['restaurant_id' => 29, 'product_id' => 15],
            ['restaurant_id' => 31, 'product_id' => 15], ['restaurant_id' => 14, 'product_id' => 16], ['restaurant_id' => 27, 'product_id' => 16],
            ['restaurant_id' => 29, 'product_id' => 16], ['restaurant_id' => 31, 'product_id' => 16], ['restaurant_id' => 32, 'product_id' => 16],
            ['restaurant_id' => 33, 'product_id' => 16], ['restaurant_id' => 34, 'product_id' => 16], ['restaurant_id' => 4, 'product_id' => 17],
            ['restaurant_id' => 5, 'product_id' => 17], ['restaurant_id' => 13, 'product_id' => 17], ['restaurant_id' => 19, 'product_id' => 17],
            ['restaurant_id' => 21, 'product_id' => 17], ['restaurant_id' => 27, 'product_id' => 17], ['restaurant_id' => 28, 'product_id' => 17],
            ['restaurant_id' => 29, 'product_id' => 17], ['restaurant_id' => 31, 'product_id' => 17], ['restaurant_id' => 2, 'product_id' => 18],
            ['restaurant_id' => 3, 'product_id' => 18], ['restaurant_id' => 6, 'product_id' => 18], ['restaurant_id' => 7, 'product_id' => 18],
            ['restaurant_id' => 8, 'product_id' => 18], ['restaurant_id' => 9, 'product_id' => 18], ['restaurant_id' => 10, 'product_id' => 18],
            ['restaurant_id' => 11, 'product_id' => 18], ['restaurant_id' => 18, 'product_id' => 18], ['restaurant_id' => 25, 'product_id' => 18],
            ['restaurant_id' => 26, 'product_id' => 18], ['restaurant_id' => 30, 'product_id' => 18], ['restaurant_id' => 4, 'product_id' => 19],
            ['restaurant_id' => 5, 'product_id' => 19], ['restaurant_id' => 13, 'product_id' => 19], ['restaurant_id' => 18, 'product_id' => 19],
            ['restaurant_id' => 19, 'product_id' => 19], ['restaurant_id' => 21, 'product_id' => 19], ['restaurant_id' => 27, 'product_id' => 19],
            ['restaurant_id' => 28, 'product_id' => 19], ['restaurant_id' => 29, 'product_id' => 19], ['restaurant_id' => 31, 'product_id' => 19],
            ['restaurant_id' => 4, 'product_id' => 20], ['restaurant_id' => 5, 'product_id' => 20], ['restaurant_id' => 13, 'product_id' => 20],
            ['restaurant_id' => 18, 'product_id' => 20], ['restaurant_id' => 19, 'product_id' => 20], ['restaurant_id' => 21, 'product_id' => 20],
            ['restaurant_id' => 27, 'product_id' => 20], ['restaurant_id' => 28, 'product_id' => 20], ['restaurant_id' => 29, 'product_id' => 20],
            ['restaurant_id' => 31, 'product_id' => 20], ['restaurant_id' => 10, 'product_id' => 21], ['restaurant_id' => 16, 'product_id' => 21],
            ['restaurant_id' => 17, 'product_id' => 21], ['restaurant_id' => 19, 'product_id' => 21], ['restaurant_id' => 21, 'product_id' => 21],
            ['restaurant_id' => 27, 'product_id' => 21], ['restaurant_id' => 1, 'product_id' => 22], ['restaurant_id' => 4, 'product_id' => 22],
            ['restaurant_id' => 19, 'product_id' => 22], ['restaurant_id' => 21, 'product_id' => 22], ['restaurant_id' => 28, 'product_id' => 22],
            ['restaurant_id' => 12, 'product_id' => 23], ['restaurant_id' => 22, 'product_id' => 23]
        ];

        foreach ($data as $row) {

            DB::table('restaurant_products')->insert($row);
        }
    }
}
