<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RestaurantSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('restaurants')->insert([
            [
                'name' => 'Kufta كوفتا',
                'address' => '42 Ankara, Sheraton Al Matar, El Nozha, Cairo Governorate 4471402',
                'phone' => '227748313',
                'email' => 'SpeakUp@sab.com',
                'latitude' => 30.10875987,
                'longitude' => 31.37535615,
                'url' => 'https://m.facebook.com/p/Kufta-%D9%83%D9%88%D9%81%D8%AA%D8%A7-100095137514140/?locale=ar_AR',
                'image_url' => 'https://i.postimg.cc/3JqD2d2T/Beef-Kofta-12.jpg',
                'country' => 'Egypt',
                'city' => 'Giza',
                'star_count' => 5,
                'rating_count' => 65,
                'primary_category_name' => 'Restaurants',
            ],
            [
                'name' => 'Spectra Restaurant & Cafe',
                'address' => 'Beside Khodeer Stationary 19 Shooting Club, Street, Dokki, Giza Governorate 3751301',
                'phone' => '+02 37626987',
                'email' => 'info@spectrarestaurant.com',
                'latitude' => 30.04601695,
                'longitude' =>31.20088217,
                'url' => 'https://spectrarestaurant.com/',
                'image_url' => 'https://i.postimg.cc/JnBTWGZc/spectra.png',
                'country' => 'Egypt',
                'city' => 'Giza',
                'star_count' => 4,
                'rating_count' => 286,
                'primary_category_name' => 'Restaurants',
            ],
            [
                'name' => 'Lobby Bar',
                'address' => 'Wahat Road opposite to El Hay El Motamayez, Giza Governorate 12451, Egypt',
                'phone' => '+20 2 38555001',
                'email' => 'hotel.cairo.mediacity@movenpick.com',
                'latitude' => 29.9653754,
                'longitude' => 31.0210765,
                'url' => 'https://www.tripadvisor.com/Restaurant_Review-g294201-d2727967-Reviews-Lobby_Bar-Cairo_Cairo_Governorate.html',
                'image_url' => 'https://i.postimg.cc/5tkCSgHn/Lobby-Bar.jpg',
                'country' => 'Egypt',
                'city' => 'Giza',
                'star_count' => 3.6,
                'rating_count' => 5,
                'primary_category_name' => 'Restaurants',

            ],
            [
                'name' => 'Al HaLLaB',
                'address' => 'مبني 24 - محل تجاري D - قطعة 1 - منطقة النوادي - حي شرق اللوتس إمتداد شارع التسعين، التجمع الخامس 2G5G+98X، قسم ثالث القاهره الجديده، محافظة القاهرة‬ 4760001, القاهرة, Cairo Governorate 11835, Egypt',
                'phone' => '+20 0217060',
                'email' => 'info@alhallabeg.com',
                'latitude' => 30.0084281,
                'longitude' => 31.5259382,
                'url' => 'https://alhallabeg.com/en/',
                'image_url' => 'https://i.postimg.cc/1t5vfJkB/Al-Ha-LLa-B.jpg',
                'country' => 'Egypt',
                'city' => 'Cairo',
                'star_count' => 4.5,
                'rating_count' => 365,
                'primary_category_name' => 'Restaurants',
            ],
            [
                'name' => 'مطعم ومخيمات القلعة',
                'address' => 'W5WQ+JGH, طريق سقارة السياحي .شبرامنت المريوطيه كوبري السحارة, Al Haram, Giza Governorate, Egypt',
                'phone' => '+20 11 46444933',
                'email' => 'support@khoroga.com',
                'latitude' => 29.9465689,
                'longitude' => 31.1888702,
                'url' => 'https://khoroga.com/ar/places/%D9%85%D8%B7%D8%A7%D8%B9%D9%85/%D9%85%D8%B7%D8%B9%D9%85-%D9%88%D9%85%D8%AE%D9%8A%D9%85%D8%A7%D8%AA-%D8%A7%D9%84%D9%82%D9%84%D8%B9%D8%A9/',
                'image_url' => 'https://i.postimg.cc/L5VfLpjZ/image.jpg',
                'country' => 'Egypt',
                'city' => 'Giza',
                'star_count' => 4,
                'rating_count' => 147,
                'primary_category_name' => 'Restaurants',
            ],
            [
                'name' => 'FREYA BRASSERIE',
                'address' => 'Abdullah ibn Salamah, New Cairo 1, Cairo Governorate 4740302, Egypt',
                'phone' => '+20 10 29099977',
                'email' => 'Terrenal@escahospitality.com',
                'latitude' => 30.0464503,
                'longitude' => 31.4838676,
                'url' => 'https://www.escahospitality.com/freya',
                'image_url' => 'https://i.postimg.cc/hPzcXrgK/FREYA-BRASSERIE.jpg',
                'country' => 'Egypt',
                'city' => 'Cairo',
                'star_count' => 3.7,
                'rating_count' => 58,
                'primary_category_name' => 'Restaurants',
            ],
            [
                'name' => 'Gingko',
                'address' => 'Nile City Towers 2005 B Corniche El Nil، Cairo Governorate 11311, Cairo Governorate 11311, Egypt',
                'phone' => '+20 2 24619494',
                'email' => 'reservations@fairmont.com',
                'latitude' => 30.0712487,
                'longitude' => 31.2273062,
                'url' => 'https://www.fairmont.com/nile-city-cairo/',
                'image_url' => 'https://i.postimg.cc/qRFBFZ0Z/Gingko.jpg',
                'country' => 'Egypt',
                'city' => 'Giza',
                'star_count' => 4.5,
                'rating_count' => 90,
                'primary_category_name' => 'Restaurants',
            ],
            [
                'name' => 'Chickana',
                'address' => 'بجوار بيم ماركت, Nasser Al-Thawra Street الهرم ٨ ش ناصر الثورة, Al Haram, Giza Governorate 12556, Egypt',
                'phone' => '+20 2 26706443',
                'email' => 'chickanaegypt@gmail.com',
                'latitude' => 30.0061602,
                'longitude' => 31.1895913,
                'url' => 'http://chickana-egypt.com/',
                'image_url' => 'https://i.postimg.cc/1XHSQCZQ/Chickana.jpg',
                'country' => 'Egypt',
                'city' => 'Giza',
                'star_count' => 3.5,
                'rating_count' => 62,
                'primary_category_name' => 'Restaurants',
            ],
            [
                'name' => 'La Terrace',
                'address' => 'St President Hotel، 22 Taha Hussein, Abu Al Feda, Zamalek, Cairo Governorate 4271150, Egypt',
                'phone' => '+20 12 73551573',
                'email' => 'info@thepresidentcairo.com',
                'latitude' => 30.0675067,
                'longitude' => 31.2195528,
                'url' => 'https://www.facebook.com/laterraceph/',
                'image_url' => 'https://i.postimg.cc/1z5Y52WW/La-Terrace.jpg',
                'country' => 'Egypt',
                'city' => 'Giza',
                'star_count' => 4.4,
                'rating_count' => 490,
                'primary_category_name' => 'Restaurants',
            ],
            [
                'name' => 'Maison Thomas - Rehab',
                'address' => 'Mall 1, Second New Cairo, Cairo Governorate 4750241, Egypt',
                'phone' => '+20 2 26925355',
                'email' => 'hello@masionthomas.net',
                'latitude' => 30.0589316,
                'longitude' => 31.4957346,
                'url' => 'http://www.maisonthomas.net/',
                'image_url' => 'https://i.postimg.cc/0yNp6vsJ/Maison-Thomas-Rehab.jpg',
                'country' => 'Egypt',
                'city' => 'Cairo',
                'star_count' => 3.5,
                'rating_count' => 54,
                'primary_category_name' => 'Restaurants',

            ],
            [
                'name' => 'BtoB Breakfast to Breakfast',
                'address' => '26 July, First 6th of October, Giza Governorate 3290301, Egypt',
                'phone' => '+20 12 05003600',
                'email' => 'info@btob-eg.com',
                'latitude' => 30.0074898,
                'longitude' => 30.9938988,
                'url' => 'http://www.btob-eg.com/',
                'image_url' => 'https://i.postimg.cc/1XHSQCZQ/Chickana.jpg',
                'country' => 'Egypt',
                'city' => 'Giza',
                'star_count' => 4.7,
                'rating_count' => 70,
                'primary_category_name' => 'Restaurants',
            ],
            [
                'name' => 'Oishi',
                'address' => 'Opposite To, Wahat Road, Mall of Egypt Rd, Elhay Elmotamayez, Giza Governorate, Egypt',
                'phone' => '+20 10 99997316',
                'email' => 'hotel.cairo.mediacity@movenpick.com',
                'latitude' => 29.9654478,
                'longitude' => 31.0208339,
                'url' => 'https://movenpick.accor.com/en/africa/egypt/cairo/hotel-cairo-media-city/restaurants/oishi-sushi---more.html?y_source=1_MTAwODM1Njk2My03MTUtbG9jYXRpb24ud2Vic2l0ZQ%3D%3D',
                'image_url' => 'https://i.postimg.cc/HsyqfqKX/Oishi.png',
                'country' => 'Egypt',
                'city' => 'Giza',
                'star_count' => 5,
                'rating_count' => 13,
                'primary_category_name' => 'Restaurants',
            ],
            [
                'name' => 'Dawar el-arab',
                'address' => '١٢ Haroun, Ad Doqi A, Dokki, Giza Governorate 12611, Egypt',
                'phone' => '+20 10 99050090',
                'email' => 'info@dawwarelarab.net',
                'latitude' => 30.0333164,
                'longitude' => 31.2156019,
                'url' => 'https://dawarelarab.net/',
                'image_url' => 'https://i.postimg.cc/CxfxrrCQ/Dawar-el-arab.jpg',
                'country' => 'Egypt',
                'city' => 'Giza',
                'star_count' => 4,
                'rating_count' => 133,
                'primary_category_name' => 'Restaurants',
            ],
            [
                'name' => 'Buffalo Burger',
                'address' => '52 El-Batal Ahmed Abd El-Aziz, Al Huwaiteyah, Agouza, Giza Governorate 3751441',
                'phone' => '+20 0219914', 
                'email' => null, 
                'latitude' => 30.02281402,
                'longitude' => 31.22559742,
                'url' => 'https://buffaloburger.com/branches/all/home',
                'image_url' => 'https://i.postimg.cc/gJKhCprk/buffalo.png',
                'country' => 'Egypt',
                'city' => 'Giza',
                'star_count' => 4.8, 
                'rating_count' => 765, 
                'primary_category_name' => 'Restaurants',

            ],
            [
                'name' => 'Second Cup',
                'address' => '26R6+666, Mossadak, Ad Doqi, Dokki, Giza Governorate 3751134',
                'phone' => '012 22327885',
                'email' => null, 
                'latitude' => 30.04067267,
                'longitude' => 31.21065269,
                'url' => 'https://secondcup.com/',
                'image_url' => 'https://i.postimg.cc/g2dDrG6d/Second-Cup.png',
                'country' => 'Egypt',
                'city' => 'Giza',
                'star_count' => 4.2, 
                'rating_count' => 259, 
                'primary_category_name' => 'Café',
            ],
            [
                'name' => "Primo's Pizza",
                'address' => 'Mecca El-Mokarrama, Ad Doqi, Dokki, Giza Governorate 3751401',
                'phone' => null, 
                'email' => null,
                'latitude' => 30.04845009,
                'longitude' => 31.20086578,
                'url' => 'https://www.facebook.com/primospizzame/', 
                'image_url' => 'https://i.postimg.cc/HWXvLZPw/Primo-s-Pizza.jpg',
                'country' => 'Egypt',
                'city' => 'Giza',
                'star_count' => 4.3, 
                'rating_count' => 22, 
                'primary_category_name' => 'Restaurants',
            ],
            [
                'name' => "Vinny's Pizza",
                'address' => '2 Taha Hussien, street, Cairo Governorate 11211',
                'phone' => '02 00219867',
                'email' => null, 
                'latitude' => 30.06393501,
                'longitude' => 31.22009151,
                'url' => 'https://www.facebook.com/vinnyscairo/', 
                'image_url' => 'https://i.postimg.cc/2SMX6smx/Screenshot-1.png',
                'country' => 'Egypt',
                'city' => 'Cairo',
                'star_count' => 4.7, 
                'rating_count' => 562, 
                'primary_category_name' => 'Restaurants',
            ],
            [
                'name' => 'Peking',
                'address' => '115 Osman Ibn Affan Street Off Triumph Square', 
                'phone' => '02 24185612', 
                'email' => null, 
                'latitude' => 30.0470841,
                'longitude' => 31.19842392,
                'url' => 'https://www.peking-eg.com/', 
                'image_url' => 'https://i.postimg.cc/7LL7F6js/Peking.jpg',
                'country' => 'Egypt',
                'city' => 'Giza',
                'star_count' => 3, 
                'rating_count' => 10, 
                'primary_category_name' => 'Restaurants',
            ],
            [
                'name' => 'Abu Mazen',
                'address' => 'أمام المنعم الموانى، ١٣ شارع الشيربين،, Soliman Gawhar, Dokki, Giza Governorate',
                'phone' => '011 01648820',
                'email' => null, 
                'latitude' => 30.03864188,
                'longitude' => 31.21306226,
                'url' => 'https://www.elmenus.com/cairo/abo-mazen-el-soury-woa5', 
                'image_url' => 'https://i.postimg.cc/s2n8zMxv/Screenshot-2.png',
                'country' => 'Egypt',
                'city' => 'Giza',
                'star_count' => 4.9, 
                'rating_count' => 458, 
                'primary_category_name' => 'Restaurants',
            ],
            [
                'name' => 'Cilantro',
                'address' => 'فندق سفير, Al Mesaha, Ad Doqi A, Dokki, Giza Governorate 3750303',
                'phone' => '012 85566297',
                'email' => null, 
                'latitude' => 30.04026149,
                'longitude' => 31.20840402,
                'url' => 'https://cilantro.cafe/', 
                'image_url' => 'https://i.postimg.cc/g0Dw2Wbw/Cilantro.png' ,
                'country' => 'Egypt',
                'city' => 'Giza',
                'star_count' => 4.5, 
                'rating_count' => 632, 
                'primary_category_name' => 'Café',

            ],
            [
                'name' => 'Al Agha',
                'address' => '148 محمد فهيم، الدقي أ، الدقى،, Dokki, Giza Governorate 12611',
                'phone' => '16316',
                'email' => null, 
                'latitude' => 30.04021201,
                'longitude' => 31.21779116,
                'url' => 'https://www.facebook.com/alaghaegypt/?locale=ar_AR', 
                'image_url' =>  'https://i.postimg.cc/dt6r0rRQ/Al-Agha.jpg',
                'country' => 'Egypt',
                'city' => 'Giza',
                'star_count' => 4.6, 
                'rating_count' => 245,
                'primary_category_name' => 'Restaurants',
            ],
            [
                'name' => 'Zi Shushi',
                'address' => '7 Fouad Abd El-latitudeif Ramadan, Ad Doqi, Dokki, Giza Governorate 3751322',
                'phone' => '010 10774701',
                'email' => null, 
                'latitude' => 30.04962259,
                'longitude' => 31.20748752,
                'url' => 'https://www.facebook.com/ZiiSushi/', 
                'image_url' => 'https://i.postimg.cc/44bBzKvq/Zi-Shushi.png',
                'country' => 'Egypt',
                'city' => 'Giza',
                'star_count' => 3, 
                'rating_count' => 12, 
                'primary_category_name' => 'Restaurants',
            ],
            [
                'name' => 'Breadfast',
                'address' => 'Consoleya 40 El-Fadl, Bab Al Louq, Abdeen, Cairo Governorate 11613',
                'phone' => null, 
                'email' => null, 
                'latitude' => 30.04956285,
                'longitude' => 31.24032192,
                'url' => 'https://www.breadfast.com/',
                'image_url' => 'https://i.postimg.cc/K8H2xpRP/Breadfast.jpg',
                'country' => 'Egypt',
                'city' => 'Cairo',
                'star_count' => 3.9, 
                'rating_count' => 125, 
                'primary_category_name' => 'Restaurants',
            ],
            [
                'name' => 'Bravo cafe',
                'address' => '55 Al Aanab, Ad Doqi, Dokki, Giza Governorate 3751411',
                'phone' => '1117473414',
                'email' => null,
                'latitude' => 30.05070105,
                'longitude' => 31.20468839,
                'url' => 'https://www.instagram.com/bravocafeoficial/reels/',
                'image_url' => 'https://i.postimg.cc/d0xZZZ9b/Bravo-cafe.png',
                'country' => 'Egypt',
                'city' => 'Giza',
                'star_count' => 4,
                'rating_count' => 32,
                'primary_category_name' => 'Restaurants',
            ],
            [
                'name' => 'GRIGIO. restaurant & cafe',
                'address' => '31 Jeddah, Ad Doqi, Dokki, Giza Governorate 3751062',
                'phone' => '1092770666',
                'email' => null, 
                'latitude' => 30.0454203,
                'longitude' => 31.1970912,
                'url' => 'https://www.facebook.com/GrigioEg/', 
                'image_url' => 'https://i.postimg.cc/8z7yrMdG/GRIGIO-restaurant-cafe.png',
                'country' => 'Egypt',
                'city' => 'Giza',
                'star_count' => 4.8, 
                'rating_count' => 190, 
                'primary_category_name' => 'Restaurants',

            ],
            [
                'name' => 'Puerto Rico Restaurant & Café',
                'address' => '5 مسجد الصحابه، الدقي، قسم الدقي،، 5 El-Sahaba Mosque, Ad Doqi, Dokki, Giza Governorate',
                'phone' => '1024590721',
                'email' => null, 
                'latitude' => 30.03969163,
                'longitude' => 31.20216316,
                'url' => 'https://m.facebook.com/p/Puerto-Rico-caf%C3%A9-and-restaurant-100070166617421/', 
                'image_url' => 'https://i.postimg.cc/g2Gzzc33/Puerto-Rico-Restaurant-Caf.jpg',
                'country' => 'Egypt',
                'city' => 'Giza',
                'star_count' => 4, 
                'rating_count' => 12,
                'primary_category_name' => 'Restaurants and Café',
            ],
            [
                'name' => 'Gad',
                'address' => 'El Tahrir, Ad Doqi, Dokki, Giza Governorate 3750275',
                'phone' => '1003293332',
                'email' => null, 
                'latitude' => 30.03780003,
                'longitude' => 31.20909148,
                'url' => 'https://www.elmenus.com/cairo/gad-w2a7', 
                'image_url' => 'https://i.postimg.cc/YSm1tx64/Gad.jpg',
                'country' => 'Egypt',
                'city' => 'Giza',
                'star_count' => 4, 
                'rating_count' => 56,
                'primary_category_name' => 'Restaurants',
            ],
            [
                'name' => 'Seekh Mashwy Dokki - سيخ مشوي الدقي',
                'address' => '106 Nile St, Ad Doqi, Dokki, Giza Governorate 12611',
                'phone' => '237605454',
                'email' => null,
                'latitude' => 30.04578141,
                'longitude' => 31.21889771,
                'url' => 'https://www.facebook.com/seekh.mashwy.restaurant/?locale=ar_AR', 
                'image_url' => 'https://i.postimg.cc/rpGvZ5D4/Seekh-Mashwy-Dokki.jpg',
                'country' => 'Egypt',
                'city' => 'Giza',
                'star_count' => 3,
                'rating_count' => 22, 
                'primary_category_name' => 'Restaurants',
            ],
            [
                'name' => 'تفويلة إملى التانك',
                'address' => 'محطه مترو, الجيزة, El Tahrir, Ad Doqi, Giza Governorate 12611',
                'phone' => '1202222731',
                'email' => null, 
                'latitude' => 30.03907903,
                'longitude' => 31.21236847,
                'url' => 'https://www.facebook.com/tafwelaeg/', 
                'image_url' => 'https://i.postimg.cc/8kYL39QR/image.png',
                'country' => 'Egypt',
                'city' => 'Giza',
                'star_count' => 3.9,
                'rating_count' => 268,
                'primary_category_name' => 'Restaurants',
            ],
            [
                'name' => 'Lusso (cafe and restaurant)',
                'address' => '493F+2XX, El-Sedeek, Sheraton Al Matar, El Nozha, Cairo Governorate 4471320',
                'phone' => null,
                'email' => null,
                'latitude' => 30.10330863,
                'longitude' => 31.37510349,
                'url' => 'https://www.instagram.com/lussoeg_cafe/',
                'image_url' => 'https://i.postimg.cc/hPbPxQrX/Lusso-cafe-and-restaurant.jpg',
                'country' => 'Egypt',
                'city' => 'Giza',
                'star_count' => 3.8,
                'rating_count' => 232 ,
                'primary_category_name' => 'Restaurants',
            ],
            [
                'name' => 'Semsema',
                'address' => '٦ Al Dokki St, Ad Doqi, Dokki, Giza Governorate 3750230',
                'phone' => '1010005100',
                'email' => null, 
                'latitude' => 30.03792053,
                'longitude' => 31.21253706,
                'url' => 'https://www.facebook.com/semsemaeg/', 
                'image_url' => 'https://i.postimg.cc/QMgBdYyy/Semsema.png',
                'country' => 'Egypt',
                'city' => 'Giza',
                'star_count' => 4.8,
                'rating_count' => 458,
                'primary_category_name' => 'Restaurants',
            ],
            [
                'name' => 'Burger King - El Manial',
                'address' => 'Nile Lounge, Abdulaziz Al Saud St',
                'phone' => '221232206',
                'email' => null, 
                'latitude' => 30.0213392,
                'longitude' => 31.22198547,
                'url' => 'https://www.bk.com/',
                'image_url' => 'https://i.postimg.cc/cJWQ4W6Y/burger-King.png',
                'country' => 'Egypt',
                'city' => 'Giza',
                'star_count' => 4.3,
                'rating_count' => 360,
                'primary_category_name' => 'Restaurants',
            ],
            [
                'name' => 'Cook Door',
                'address' => '35 Al Falki, Bab Al Louq, Abdeen, Cairo Governorate 4280123',
                'phone' => '1274974401',
                'email' => null, 
                'latitude' => 30.05113948,
                'longitude' => 31.24224112,
                'url' => 'https://cookdoor.com.eg/',
                'image_url' => 'https://i.postimg.cc/mZyyct7D/Cook-Door.png',
                'country' => 'Egypt',
                'city' => 'Cairo',
                'star_count' => 4,
                'rating_count' =>150,
                'primary_category_name' => 'Restaurants',
            ],
            [
                'name' => 'Heart attack',
                'address' => '36 Sherif Basha, Al Fawalah, Abdeen, Cairo Governorate 4280160',
                'phone' => null, 
                'email' => null, 
                'latitude' => 30.053287,
                'longitude' => 31.24169535,
                'url' => 'https://heartattack.me/',
                'image_url' => 'https://i.postimg.cc/Gttws6gh/Heart-attack.jpg',
                'country' => 'Egypt',
                'city' => 'Cairo',
                'star_count' => 4.5,
                'rating_count' => 230,
                'primary_category_name' => 'Restaurants',
            ],
            
        ]);
    }
}
